name: Deploy GitHub Pages

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 部署运行环境搭建
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0 # github代码拉取深度
      - name: Setup Node  🎬
        uses: actions/setup-node@main
        with:
          node-version: 'lts/*'
      - name: Setup pnpm
        run: |
          npm install -g pnpm
      - name: Build 🔧
        run: |
          pnpm install
          pnpm run build:pro
          ls -lrth
      - name: Deploy 🚀 # 把打包后的dist文件部署到main分支
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.TOKEN_MODERN_ADMIN }} # github setting分配相应权限并生成TOKEN秘钥,在本项目-->设置-->secrets添加 TOKEN_JV 变量 值为生成的秘钥
          branch: gh-pages
          folder: dist
